// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SayHi
{
	public partial class SayHiViewController : UIViewController
	{
		public SayHiViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
